"""
tools/report_generator.py — スキャン結果をHTMLレポートに変換

応用情報技術者・情報処理安全確保支援士試験の基準に準拠したフォーマット。
生成したレポートは reports/ ディレクトリに保存される。
"""

from __future__ import annotations
import os
import re
import html
from datetime import datetime

_CSS = """
:root {
  --bg:#070C14; --panel:#0B1220; --widget:#0E1828;
  --border:#1A3050; --cyan:#00D4FF; --green:#00FF88;
  --red:#FF3B3B; --orange:#FF7A3B; --yellow:#FFD700;
  --text:#D8E8F4; --dim:#4A6A8A; --mid:#7A9ABE;
}
*{box-sizing:border-box;margin:0;padding:0}
body{background:var(--bg);color:var(--text);
     font-family:'Segoe UI',system-ui,sans-serif;padding:32px 40px}
h2{color:var(--cyan);font-size:14px;border-bottom:1px solid var(--border);
   padding-bottom:6px;margin:28px 0 14px;text-transform:uppercase;letter-spacing:.06em}
.header{border:1px solid var(--border);border-radius:8px;
        padding:22px 28px;margin-bottom:28px;background:var(--panel)}
.header h1{color:var(--cyan);font-size:22px;letter-spacing:.04em;margin-bottom:14px}
.meta{color:var(--mid);font-size:13px;margin:4px 0}
.meta b{color:var(--text);margin-left:6px}
.summary{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin-bottom:28px}
.sev{background:var(--panel);border-radius:8px;padding:18px;text-align:center;
     border:1px solid var(--border)}
.sev .lbl{font-size:11px;font-weight:700;letter-spacing:.08em}
.sev .cnt{font-size:36px;font-weight:700;margin-top:4px}
.c .lbl,.c .cnt{color:var(--red)}
.h .lbl,.h .cnt{color:var(--orange)}
.m .lbl,.m .cnt{color:var(--yellow)}
.l .lbl,.l .cnt{color:var(--green)}
.finding{background:var(--panel);border-radius:8px;border:1px solid var(--border);
         margin-bottom:16px;overflow:hidden}
.fhdr{padding:12px 18px;border-bottom:1px solid var(--border);
      display:flex;align-items:center;gap:12px}
.fbody{padding:16px 18px}
.badge{display:inline-block;padding:3px 10px;border-radius:4px;
       font-size:11px;font-weight:700;letter-spacing:.06em}
.bCRITICAL{background:rgba(255,59,59,.15);color:var(--red);border:1px solid rgba(255,59,59,.3)}
.bHIGH{background:rgba(255,122,59,.15);color:var(--orange);border:1px solid rgba(255,122,59,.3)}
.bMEDIUM{background:rgba(255,215,0,.12);color:var(--yellow);border:1px solid rgba(255,215,0,.25)}
.bLOW{background:rgba(57,255,117,.10);color:var(--green);border:1px solid rgba(57,255,117,.2)}
.fname{font-weight:700;font-size:14px}
.fmeta{color:var(--mid);font-size:12px;margin-bottom:10px}
.fmeta b{color:var(--text)}
pre{background:var(--widget);border-radius:6px;padding:12px 14px;
    font-family:Consolas,monospace;font-size:12px;overflow-x:auto;
    border:1px solid var(--border);margin:8px 0;line-height:1.4}
.slabel{color:var(--cyan);font-size:11px;font-weight:700;
        letter-spacing:.08em;margin:12px 0 4px}
.raw{background:var(--widget);border-radius:8px;border:1px solid var(--border);
     padding:16px;font-family:Consolas,monospace;font-size:11px;
     line-height:1.5;white-space:pre-wrap;word-break:break-word;
     max-height:600px;overflow-y:auto}
footer{margin-top:36px;color:var(--dim);font-size:12px;text-align:center;
       border-top:1px solid var(--border);padding-top:16px}
"""

_TEMPLATE = """<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Security Audit Report — {title}</title>
<style>{css}</style>
</head>
<body>
<div class="header">
  <h1>&#x1F6E1; AI Security Audit Report</h1>
  <div class="meta">SCAN MODE: <b>{mode}</b></div>
  <div class="meta">TARGET: <b>{target}</b></div>
  <div class="meta">AI ENGINE: <b>{model}</b></div>
  <div class="meta">SCAN DATE: <b>{timestamp}</b></div>
  <div class="meta">GENERATED BY: <b>AI Security Audit System v2.0</b></div>
</div>
<h2>Executive Summary — Severity Distribution</h2>
<div class="summary">
  <div class="sev c"><div class="lbl">CRITICAL</div><div class="cnt">{critical}</div></div>
  <div class="sev h"><div class="lbl">HIGH</div>    <div class="cnt">{high}</div></div>
  <div class="sev m"><div class="lbl">MEDIUM</div>  <div class="cnt">{medium}</div></div>
  <div class="sev l"><div class="lbl">LOW</div>     <div class="cnt">{low}</div></div>
</div>
{findings_section}
<h2>Full Scan Output</h2>
<div class="raw">{raw}</div>
<footer>
  本レポートは AI Security Audit System により自動生成されました。<br>
  内容は参考情報です。重大な脆弱性については専門家による確誌を推奨します。<br>
  <em>本ツールは教育・研究・許可されたセキュリティ診断を目的としています。</em>
</footer>
</body>
</html>"""


def _parse(text: str, start_marker: str, end_marker: str) -> list[dict]:
    findings = []
    for block in re.findall(
        rf"{re.escape(start_marker)}(.*?){re.escape(end_marker)}", text, re.DOTALL
    ):
        def _field(key: str, b: str = block) -> str:
            m = re.search(rf"^{key}:\s*(.+)", b, re.MULTILINE)
            return m.group(1).strip() if m else ""

        snippet = re.search(r"SNIPPET:\s*```[^\n]*\n(.*?)```", block, re.DOTALL)
        fix     = re.search(r"FIX:\s*```[^\n]*\n(.*?)```",     block, re.DOTALL)
        attack  = re.search(r"ATTACK:\n(.*?)(?=\nFIX:|\Z)",     block, re.DOTALL)
        findings.append({
            "name":    _field("NAME") or _field("THREAT_TYPE"),
            "severity": _field("SEVERITY"),
            "ref":     _field("CWE") or _field("MITRE_TTP"),
            "lines":   _field("LINES") or _field("ATTACKER_IP"),
            "snippet": snippet.group(1).strip() if snippet else _field("TIMELINE"),
            "attack":  attack.group(1).strip()  if attack  else "",
            "fix":     fix.group(1).strip()     if fix     else "",
        })
    return findings


def _render_finding(f: dict) -> str:
    sev  = (f.get("severity") or "LOW").upper()
    name = html.escape(f.get("name") or "Unknown")
    bc   = f"b{sev}" if sev in ("CRITICAL", "HIGH", "MEDIUM", "LOW") else "bLOW"
    meta_parts = [
        f"<b>{k}:</b> {html.escape(v)}"
        for k, v in [("REF", f.get("ref", "")), ("LOCATION", f.get("lines", ""))]
        if v
    ]
    parts = []
    if f.get("snippet"):
        parts.append(f'<div class="slabel">VULNERABLE CODE</div><pre>{html.escape(f["snippet"])}</pre>')
    if f.get("attack"):
        parts.append(f'<div class="slabel">ATTACK / ANALYSIS</div><pre>{html.escape(f["attack"])}</pre>')
    if f.get("fix"):
        parts.append(f'<div class="slabel">RECOMMENDED FIX</div><pre>{html.escape(f["fix"])}</pre>')
    return (
        f'<div class="finding">'
        f'<div class="fhdr"><span class="badge {bc}">{sev}</span>'
        f'<span class="fname">{name}</span></div>'
        f'<div class="fbody">'
        f'<div class="fmeta">{" &nbsp;|&nbsp; ".join(meta_parts)}</div>'
        f'{"".join(parts)}</div></div>'
    )


def generate(
    mode: str,
    target: str,
    raw_text: str,
    model: str = "Unknown",
    timestamp: str | None = None,
) -> str:
    """スキャン結果をHTMLレポートとして生成して文字列で返す。"""
    if timestamp is None:
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    if "DEFENSE" in mode.upper():
        findings = _parse(raw_text, "---THREAT_START---", "---THREAT_END---")
    else:
        findings = _parse(raw_text, "---VULN_START---", "---VULN_END---")

    counts: dict[str, int] = {"CRITICAL": 0, "HIGH": 0, "MEDIUM": 0, "LOW": 0}
    for f in findings:
        sev = (f.get("severity") or "LOW").upper()
        if sev in counts:
            counts[sev] += 1

    findings_section = ""
    if findings:
        rendered = "\n".join(_render_finding(f) for f in findings)
        findings_section = f"<h2>Detailed Findings ({len(findings)})</h2>\n{rendered}"

    return _TEMPLATE.format(
        css=_CSS,
        title=html.escape(os.path.basename(target) if target else mode),
        mode=html.escape(mode),
        target=html.escape(target or "—"),
        model=html.escape(model),
        timestamp=html.escape(timestamp),
        findings_section=findings_section,
        raw=html.escape(raw_text),
        **counts,
    )


def save(html_content: str, mode: str, reports_dir: str = "reports") -> str:
    """レポートをファイルに保存してパスを返す。"""
    os.makedirs(reports_dir, exist_ok=True)
    ts   = datetime.now().strftime("%Y%m%d_%H%M%S")
    slug = re.sub(r"[^a-z0-9]", "_", mode.lower())[:20]
    path = os.path.join(reports_dir, f"report_{slug}_{ts}.html")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(html_content)
    return path
